### PR TITLE
Candela release version

### PR DESCRIPTION
**Pull request by KemanDragon**
Unable to do a PR for the original so I've forked it instead, with the goal of updating this sheet to work for the fully released game.

### CODE REVIEW

**Comment by KemanDragon** [comment]
I'm not sure if this repo is watched anymore but I've started adding to the sheet to update to the release version. If you see this let me know if you'd rather I do PRs here or if you're okay with me just forking this.

**Comment by nuadaria** [comment]
Awesome. Glad to see someone else interested. I don't mind the fork at all as I haven't yet picked up the full book.

**Comment by KemanDragon** [comment]
Awesome. I'll just continue work on the fork I've got then. Cheers.

**Comment by KemanDragon** [comment]
Looks like they have added official support, so there's little reason to continue this

**Pull request merged**
